### ISSUE TITLE
Download Error with Episode 113 of My Hero Acadamia

### ISSUE THREAD

**Issue by 619beave** [hama3254/Crunchyroll-Downloader-v3.0#365]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.8.0.01 Chromium-Hotfix-#357_3

Please provide a logfile or text.

<details>
  <summary>Log</summary>

Thread Name: Main
Web server started at: 127.0.0.1:8080
Start loading: 10/9/2021 4:14:53 PM
get html
10/9/2021 4:14:53 PM.930
https://www.funimation.com/v/my-hero-academia/the-high-deep-blue-sky?lang=english
3
Thread Name: 
processing :https://title-api.prd.funimationsvc.com/v1/shows/my-hero-academia/episodes/the-high-deep-blue-sky/?region=US&deviceType=web&locale=en
https://title-api.prd.funimationsvc.com/v1/shows/my-hero-academia/episodes/the-high-deep-blue-sky/?region=US&deviceType=web&locale=en
error- getting v1Json data
System.Net.WebException: The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Crunchyroll_Downloader.Main.GetFunimationJS_Video(String v1JsonUrl, String v1JsonData) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:line 4818
get html
10/9/2021 4:15:05 PM.476
https://title-api.prd.funimationsvc.com/v1/shows/my-hero-academia/episodes/the-high-deep-blue-sky/?region=US&deviceType=web&locale=en

v1Json: {"duration": 1430, "name": "The High, Deep Blue Sky", "sequence": 116, "mature": false, "shortCode": "S5 E113", "season": {"number": 5, "type": "season", "name": "Season 5", "slug": "season-5-10", "id": 1393274}, "ratings": [{"ratingSystem": "TV-US", "id": 1, "mature": false, "ratingCode": "TV-14"}], "releaseDate": 1632528000000, "id": 1635784, "durationInMinutes": 23, "showId": 124389, "slug": "the-high-deep-blue-sky", "contentId": "MHA0113", "videoList": [{"type": "simulcast", "videoInstances": [{"language": {"name": "English", "languageCode": "en", "id": 10}, "title": "09e468c6-7e44-4a28-a357-2f3614a9111f_index.m3u8", "type": "video", "ext": "m3u8", "id": 2833254, "filePath": "https://d33et77evd9bgg.cloudfront.net/exp/FunimationStoreFront/V2429083/09e468c6-7e44-4a28-a357-2f3614a9111f_index.m3u8"}, {"language": {"name": "English", "languageCode": "en", "id": 10}, "title": "09e468c6-7e44-4a28-a357-2f3614a9111f_index.mp4", "type": "video", "ext": "mp4", "id": 2833255, "filePath": "https://d33et77evd9bgg.cloudfront.net/exp/FunimationStoreFront/V2429083/09e468c6-7e44-4a28-a357-2f3614a9111f_index.mp4"}, {"language": {"name": "English", "languageCode": "en", "id": 10}, "title": "audio track", "type": "audio", "ext": "m3u8", "id": 2833256, "filePath": "https://d33et77evd9bgg.cloudfront.net/exp/FunimationStoreFront/V2429083/09e468c6-7e44-4a28-a357-2f3614a9111f_index.m3u8"}], "hardsubbed": false, "id": 2833252, "subtitleLanguages": [], "videoRights": [{"endDate": 2145916800000, "startDate": 1633771800000, "id": 801566, "right": {"id": 2, "name": "SVOD"}}], "spokenLanguages": [{"name": "English", "languageCode": "en", "id": 10}], "downloadable": false}, {"type": "simulcast", "videoInstances": [{"language": {"name": "Japanese", "languageCode": "ja", "id": 23}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_index.m3u8", "type": "video", "ext": "m3u8", "id": 2491394, "filePath": "https://d33et77evd9bgg.cloudfront.net/exp/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_index.m3u8"}, {"language": {"name": "Japanese", "languageCode": "ja", "id": 23}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_index.mp4", "type": "video", "ext": "mp4", "id": 2491395, "filePath": "https://d33et77evd9bgg.cloudfront.net/exp/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_index.mp4"}, {"language": {"name": "Japanese", "languageCode": "ja", "id": 23}, "title": "audio track", "type": "audio", "ext": "m3u8", "id": 2491396, "filePath": "https://d33et77evd9bgg.cloudfront.net/exp/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_index.m3u8"}, {"language": {"name": "English", "languageCode": "en", "id": 10}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_english_full.vtt", "type": "subtitle", "ext": "vtt", "id": 2491397, "filePath": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_english_full.vtt"}, {"language": {"name": "Spanish (Latin Am)", "languageCode": "es", "id": 62}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_spanishlatinamerica_full.vtt", "type": "subtitle", "ext": "vtt", "id": 2491398, "filePath": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_spanishlatinamerica_full.vtt"}, {"language": {"name": "Portuguese (Brazil)", "languageCode": "pt", "id": 61}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_portuguesebrazil_full.vtt", "type": "subtitle", "ext": "vtt", "id": 2491399, "filePath": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_portuguesebrazil_full.vtt"}, {"language": {"name": "English", "languageCode": "en", "id": 10}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_english_full.srt", "type": "subtitle", "ext": "srt", "id": 2491400, "filePath": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_english_full.srt"}, {"language": {"name": "Spanish (Latin Am)", "languageCode": "es", "id": 62}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_spanishlatinamerica_full.srt", "type": "subtitle", "ext": "srt", "id": 2491401, "filePath": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_spanishlatinamerica_full.srt"}, {"language": {"name": "Portuguese (Brazil)", "languageCode": "pt", "id": 61}, "title": "9961d5a0-0239-4376-98a6-b49407a200d3_portuguesebrazil_full.srt", "type": "subtitle", "ext": "srt", "id": 2491402, "filePath": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2429083/9961d5a0-0239-4376-98a6-b49407a200d3_portuguesebrazil_full.srt"}], "hardsubbed": false, "id": 2491370, "subtitleLanguages": [{"name": "English", "languageCode": "en", "id": 10}, {"name": "Portuguese (Brazil)", "languageCode": "pt", "id": 61}, {"name": "Spanish (Latin Am)", "languageCode": "es", "id": 62}], "videoRights": [{"endDate": 2145916800000, "startDate": 1633167000000, "id": 792404, "right": {"id": 1, "name": "AVOD"}}, {"endDate": 2145916800000, "startDate": 1632562200000, "id": 792415, "right": {"id": 2, "name": "SVOD"}}], "spokenLanguages": [{"name": "Japanese", "languageCode": "ja", "id": 23}], "downloadable": false}], "show": {"name": "My Hero Academia", "id": 124389, "slug": "my-hero-academia", "type": "tv"}, "synopsis": "Both sides prepare for the confrontation between the heroes and the Paranormal Liberation Front as Class 1-A finishes their first year of high school. ", "externalEpisodeId": "MHA0113", "episodeNumber": "113", "qualities": [{"quality": "SD", "height": 540}], "versions": ["simulcast"], "images": [{"key": "showThumbnail", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2148083/English/2148083_English_ShowThumbnail_e7624f68-8944-ea11-82a8-dd291e252010.jpg"}, {"key": "showBackgroundSite", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358911/Japanese/2358911_Japanese_ShowBackgroundSite_d01e87ac-62ae-440e-9cf6-62de1ff5c499.jpg"}, {"key": "showDetailHeaderDesktop", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2148083/English/2148083_English_ShowDetailHeaderDesktop_e3624f68-8944-ea11-82a8-dd291e252010.jpg"}, {"key": "showKeyart", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358911/Japanese/2358911_Japanese_ShowKeyart_48e464b7-8642-430e-ae18-4cfbd191744a.jpg"}, {"key": "appleHorizontalBannerShow", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1394249/Latvian/1394249_Latvian_AppleHorizontalBannerShow_4a87c5e4-5511-4c2b-a805-738edc401885.png"}, {"key": "backgroundImageXbox360", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358911/Japanese/2358911_Japanese_ShowBackgroundGreyXbox360_034e9548-4b09-41cb-8dbc-9719615aa164.png"}, {"key": "continueWatchingMobile", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358911/Japanese/2358911_Japanese_ContinueWatchingMobile_211aedc9-b1f7-4451-812b-41d98a7139a0.jpg"}, {"key": "showDetailBoxArtTablet", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_ShowDetailHeroTablet_820d2103-dd90-4214-a48a-ffb1f7493cc7.jpg"}, {"key": "backgroundImageAppletvfiretv", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358905/Japanese/2358905_Japanese_ShowBackground_d647f068-2fb5-4563-ab7c-750b966d1e26.jpg"}, {"key": "newShowDetailHero", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358911/Japanese/2358911_Japanese_NewShowDetailHero_908acae7-6ba2-4c07-a306-d47a576aa769.jpg"}, {"key": "continueWatchingDesktop", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_1BLANK_ContinueWatchingDesktop_a0c9c8e7-ee33-41d8-ad33-40c9caf25fd5.jpg"}, {"key": "applePosterCover", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1394249/Latvian/1394249_Latvian_ApplePosterCover_c1a88039-bad5-ea11-82a8-dd291e252010.jpg"}, {"key": "featuredSpotlightShowPhone", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_FeaturedSpotlightShowPhone_09909da8-c6ff-4f11-9480-a30d30f2e9dc.jpg"}, {"key": "featuredSpotlightShowTablet", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_FeaturedSpotlightShowTablet_376c35fc-366e-4447-8268-42b42dc01d87.jpg"}, {"key": "showDetailBoxArtPhone", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358905/Japanese/2358905_Japanese_ShowDetailHeroPhone_8014db86-3efb-4b3c-8355-36dab4781d5c.jpg"}, {"key": "appleSquareCover", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_Show_Box_3000x3000_aeb65189-ad0f-45fe-af0a-ae73ab0c1621.jpg"}, {"key": "backgroundVideo", "path": "https://d2od7wv95xp0d4.cloudfront.net/videos/20cf89a4-86bb-4b8e-9472-0a6c552c3262.mp4"}, {"key": "showMasterKeyArt", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_ShowMasterKeyArt2x3_4a0fd57d-f26f-41ff-b527-6fa537c19e64.jpg"}, {"key": "newShowDetailHeroPhone", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1605008/4c45214a-60d8-48ec-af32-81c6a54eb44a/1605008_MHA_NewShowDetailHeroPhone_34a42f63-c5f2-4e9e-807f-8dabe86621cb.jpg"}, {"key": "showDetailBoxArtXbox360", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2148083/English/2148083_English_ShowDetailHeroXbox360_e5624f68-8944-ea11-82a8-dd291e252010.jpg"}, {"key": "showDetailHeaderMobile", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/1394249/Latvian/1394249_Latvian_ShowDetailHeaderMobile_0701cba8-f879-ea11-82a8-dd291e252010.jpg"}, {"key": "showLogo", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/2358905/Japanese/2358905_Japanese_ShowLogo_20f57e8f-d412-4713-9841-34c257d0ef53.png"}, {"key": "episodeThumbnail", "path": "https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/100005219/28203c46-ad4f-4541-8840-7fc8d602d784/100005219_MHA0113_dbc556d7-2a6e-47fb-a030-c2a1a6b7b034.jpg"}], "type": "episode", "isSubRequired": false}
FunimationSeason: Season 5
FunimationTitle: My Hero Academia
E:\Downloads\
error- getting funimation showexperience data
got error browser html
10/9/2021 4:15:06 PM.951
https://www.funimation.com/api/showexperience/2833252/?pinst_id=fzQc9p9f  

</details>

Note: Please keep in mind, so far episode 113 of My Hero Acadamia only has this issue with me.

Screenshot below:
![Screenshot 2021-10-09 13 16 55](https://user-images.githubusercontent.com/41927382/136676025-0174adfa-a72d-49b2-87ff-ad24b67932b2.png)
,

**Comment by 619beave** [comment]
I wouls also like to add, this happens in English Dub. Japanese Audio works fine.
