### ISSUE TITLE
Doesnt start correctly

### ISSUE THREAD

**Issue by xILikepuddingx** [hama3254/Crunchyroll-Downloader-v3.0#475]
hi

I have a small problem
the program does not open correctly.

but i do not know why.
I would be very grateful for any help

https://i.imgur.com/rc6DPHT.png

<details>
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.Runtime.dll'
   at CefSharp.CefSettingsBase..ctor()
   at Crunchyroll_Downloader.Main.Form8_Load(Object sender, EventArgs e) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:line 363
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at MetroFramework.Forms.MetroForm.OnLoad(EventArgs e) in D:\Projecte\Crunchyroll Downloader - v3.0-final\metroframework-modern-ui\MetroFramework\Forms\MetroForm.cs:line 471
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at MetroFramework.Forms.MetroForm.WndProc(Message& m) in D:\Projecte\Crunchyroll Downloader - v3.0-final\metroframework-modern-ui\MetroFramework\Forms\MetroForm.cs:line 585
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4480.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Crunchyroll Downloader
    Assembly Version: 3.8.6.0
    Win32 Version: 3.8.6.0
    CodeBase: file:///C:/Users/…./Desktop/Crunchy/Crunchyroll%20Downloader.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4480.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Users/…./Desktop/Crunchy/lib/MetroFramework.DLL
----------------------------------------
CefSharp.WinForms
    Assembly Version: 100.0.140.0
    Win32 Version: 100.0.140.0
    CodeBase: file:///C:/Users/…./Desktop/Crunchy/lib/CefSharp.WinForms.DLL
----------------------------------------
CefSharp.Core
    Assembly Version: 100.0.140.0
    Win32 Version: 100.0.140.0
    CodeBase: file:///C:/Users/…./Desktop/Crunchy/lib/CefSharp.Core.DLL
----------------------------------------
CefSharp
    Assembly Version: 100.0.140.0
    Win32 Version: 100.0.140.0
    CodeBase: file:///C:/Users/…./Desktop/Crunchy/lib/CefSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```
  <summary> Click me
</summary>
</details>

**Comment by hama3254** [comment]
You probably miss the [Microsoft Visual C++ Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) just get the x64 version or [use this direct link](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by xILikepuddingx** [comment]
hi,

yes this problem has been fixed now. thank you very much

unfortunately, the next problem comes directly:
I try to download something nothing happens.
https://i.imgur.com/hDY1g3I.png
https://i.imgur.com/Ib01xJD.png
https://i.imgur.com/JD5w1wR.png

from here on nothing happens. no matter how long i wait.

a click on the status also only showed this:
https://i.imgur.com/IUa0Vag.png

**Comment by hama3254** [comment]
check your settings to see if you did not set the download count to 0

**Comment by xILikepuddingx** [comment]
weird thing

i didn't actually change anything. was really on 0. I am embarrassed now....

i think this time i really have a bug

https://www.crunchyroll.com/de/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made
https://beta.crunchyroll.com/de/series/G9VHN9DDX/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made

both links are actually the same. with the beta the download doesn't start. It is in a loading loop

https://i.imgur.com/OFhUaGo.png

**Comment by hama3254** [comment]
That is due to crunchyrolls behavior, they don't redirect beta anime to the appropriate classic page just the other way around.
to fix that you can either use the classic url or you have to login with your account that has access to the beta.

**Comment by xILikepuddingx** [comment]
ah i see
thank you very much for ur help and effort x3
