### ISSUE TITLE
fatal! Failed to download 'encryption key'

### ISSUE THREAD

**Issue by 619beave** [hama3254/Crunchyroll-Downloader-v3.0#990]
**Describe the bug**

**Where does the issue happen?**
 When downloading Unnamed Memory Episode 11

Using version 3.24.0

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/41927382/79012a84-b9b9-4df6-bbcd-69fddd4e037e)

**Additional context**
v3.24.0
Thread Name: Main
what's going on?: 6/18/2024 8:24:08 AM
StatusLabel: 6/18/2024 8:24:08 AM - Status: using login to authenticate
StatusLabel: 6/18/2024 8:24:11 AM - Status: Url match - Anime episode
ObjectsUrl: https://beta-api.crunchyroll.com/content/v2/cms/objects/GK9U3EV5Q?preferred_audio_language=en-US&locale=en-US
Website: https://www.crunchyroll.com/watch/GK9U3EV5Q/castle-of-sand
6/18/2024 8:24:12 AM CR-Title: Castle of Sand
NewAPI: https://cr-play-service.prd.crunchyrollsvc.com/v1/GK9U3EV5Q/console/switch/play
StatusLabel: 6/18/2024 8:24:13 AM - Status: API data received
0 Streams-1988: en-US fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589337.mp4,5589346.mp4,5589328.mp4,5589310.mp4,5589319.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
1 Streams-1988: de-DE fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589344.mp4,5589353.mp4,5589335.mp4,5589317.mp4,5589326.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
2 Streams-1988: es-419 fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589338.mp4,5589347.mp4,5589329.mp4,5589311.mp4,5589320.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
3 Streams-1988: es-ES fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589339.mp4,5589348.mp4,5589330.mp4,5589312.mp4,5589321.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
4 Streams-1988: fr-FR fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589340.mp4,5589349.mp4,5589331.mp4,5589313.mp4,5589322.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
5 Streams-1988: it-IT fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589343.mp4,5589352.mp4,5589334.mp4,5589316.mp4,5589325.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
6 Streams-1988: pt-BR fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589341.mp4,5589350.mp4,5589332.mp4,5589314.mp4,5589323.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
7 Streams-1988: ru-RU fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589345.mp4,5589354.mp4,5589336.mp4,5589318.mp4,5589327.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
8 Streams-1988: ar-SA fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589342.mp4,5589351.mp4,5589333.mp4,5589315.mp4,5589324.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
9 Streams-1988: null fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5582655.mp4,5582656.mp4,5582654.mp4,5582652.mp4,5582653.mp4,.urlset/master.m3u8?playbackGuid=11-f97f0459-4d69-43e0-9a66-c5c7bd699acc&accountid=217c990b-afd9-540d-a973-bd48e7d87ca0
StatusLabel: 6/18/2024 8:24:13 AM - Status: Language found
 Unnamed Memory Season 1 Episode 11 Castle of Sand
X:\Downloads\
Checking chapters
CurlError: curl: (22) The requested URL returned error: 403

Checking chapters ended
StatusLabel: 6/18/2024 8:24:14 AM - Status: Resolution found
Delete Token: 11-f97f0459-4d69-43e0-9a66-c5c7bd699acc for GK9U3EV5Q - Unnamed Memory Season 1 Episode 11 Castle of Sand
StatusLabel: 6/18/2024 8:24:16 AM - Status: Checking Soft-Subs
Softsubs Default: None
ThumbnialURL: https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/fa1886326b0ff75e1eea97111cd7eb6c.jpe
T:\Temp\CRD-Temp-File-BHZDCMFdSGDOFgNf\
Download error #1: T:\Temp\CRD-Temp-File-BHZDCMFdSGDOFgNf\CRD-Temp-File-MdfQKMKeRDceFKTe.key
Download error #2: https:///T:/CR%20Portable/skd://drmtoday?assetId=9dff046ab7ddec78a0148f42b5003c15&variantId=avkey
T:\Temp\CRD-Temp-File-BHZDCMFdSGDOFgNf\CRD-Temp-File-MdfQKMKeRDceFKTe.key
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Crunchyroll_Downloader.CRD_List_Item.TS_DownloadAsync(String DL_URL, String DL_Pfad) in C:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\CRD_List_Item.vb:line 1079
https:///T:/CR%20Portable/skd://drmtoday?assetId=9dff046ab7ddec78a0148f42b5003c15&variantId=avkey

Also, tried closing the program many times.  The CRD stays loaded as a background process.

TRied downloading another amine, get:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/41927382/5a44c74b-c8c9-4409-9da4-8534d1ab9955)

**Comment by hama3254** [comment]
both downloads run into a DRM stream `skd://drmtoday` i have to see why.

**Comment by Akamaru** [comment]
Not sure if it's the same error but I got this:
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/8063440/5a06aebc-6d2c-48ae-a227-5af90bf4fef2)
```text

v3.24.0
Thread Name: Main
what's going on?: 18.06.2024 17:57:21
StatusLabel: 18.06.2024 17:57:21 - Status: using login to authenticate
StatusLabel: 18.06.2024 17:57:24 - Status: Url match - Anime episode
ObjectsUrl: https://beta-api.crunchyroll.com/content/v2/cms/objects/GK9U3EV5Q?preferred_audio_language=ja-JP&locale=de-DE
Website: https://www.crunchyroll.com/de/watch/GK9U3EV5Q/castle-of-sand
18.06.2024 17:57:26 CR-Title: Ein Schloss aus Sand
NewAPI: https://cr-play-service.prd.crunchyrollsvc.com/v1/GK9U3EV5Q/console/switch/play
StatusLabel: 18.06.2024 17:57:26 - Status: API data received
0 Streams-1988: en-US fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589337.mp4,5589346.mp4,5589328.mp4,5589310.mp4,5589319.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
1 Streams-1988: de-DE fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589344.mp4,5589353.mp4,5589335.mp4,5589317.mp4,5589326.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
2 Streams-1988: es-419 fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589338.mp4,5589347.mp4,5589329.mp4,5589311.mp4,5589320.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
3 Streams-1988: es-ES fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589339.mp4,5589348.mp4,5589330.mp4,5589312.mp4,5589321.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
4 Streams-1988: fr-FR fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589340.mp4,5589349.mp4,5589331.mp4,5589313.mp4,5589322.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
5 Streams-1988: it-IT fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589343.mp4,5589352.mp4,5589334.mp4,5589316.mp4,5589325.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
6 Streams-1988: pt-BR fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589341.mp4,5589350.mp4,5589332.mp4,5589314.mp4,5589323.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
7 Streams-1988: ru-RU fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589345.mp4,5589354.mp4,5589336.mp4,5589318.mp4,5589327.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
8 Streams-1988: ar-SA fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5589342.mp4,5589351.mp4,5589333.mp4,5589315.mp4,5589324.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
9 Streams-1988: null fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3EV5Q/evs3/83c68b5e3560429eb78aeccbe55757b2/assets/p/9dff046ab7ddec78a0148f42b5003c15_,5582655.mp4,5582656.mp4,5582654.mp4,5582652.mp4,5582653.mp4,.urlset/master.m3u8?playbackGuid=08-26f131e5-3870-4a0a-bd86-00948512e5b0&accountid=017e8430-222e-51ed-a9ac-4744df241ab0
StatusLabel: 18.06.2024 17:57:26 - Status: Language found
 Unnamed Memory  E11 Ein Schloss aus Sand
H:\Festplatten\Nebulak\Downloads\anime\
Checking chapters
CurlError: curl: (22) The requested URL returned error: 403

Checking chapters ended
StatusLabel: 18.06.2024 17:57:28 - Status: Resolution found
Delete Token: 08-26f131e5-3870-4a0a-bd86-00948512e5b0 for GK9U3EV5Q - Unnamed Memory E11 Ein Schloss aus Sand
StatusLabel: 18.06.2024 17:57:31 - Status: Checking Soft-Subs
Softsubs Default: de-DE
-disposition:s: 0
ThumbnialURL: https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/fa1886326b0ff75e1eea97111cd7eb6c.jpe

```

**Comment by hama3254** [comment]
This and #991 are the result of the stream now being DRM protected.
For more discussion please use #991.
